"""
Revision ID: 1db405b561d7
Revises: add_food_log_analysis
Create Date: 2025-07-02 18:56:16.524840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1db405b561d7'
down_revision = 'add_food_log_analysis'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food_log_analyses', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('food_log_analyses', 'food_log_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('food_log_analyses', 'health_score',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.create_unique_constraint('uq_user_food_log_analysis', 'food_log_analyses', ['user_id', 'food_log_id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_food_log_analysis', 'food_log_analyses', type_='unique')
    op.alter_column('food_log_analyses', 'health_score',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=True)
    op.alter_column('food_log_analyses', 'food_log_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('food_log_analyses', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ### 